### ISSUE TITLE
notification is too chatty

### ISSUE THREAD

**Issue by Ferritt1975** [microtodd/servercanary#11]
the LB from each AZ will hit the canary one time every interval (i.e., 15 seconds).  it will do this some number of times corresponding with the threshold.   So, its possible the caranry will notify many times.  this is unncessary.  the caranry should notify one time and provide no further notificaitons.

alternatively, it should continue to notifiy, but not more than every so often, and possibly include a duration since the first notificaiton

"Service X is offline, and has been that way for xxx seconds..."

**Comment by microtodd** [comment]
So like an "alert window" as I call it.  i.e. if I report an alert, don't report another alert for at least X minutes.  I've seen this behavior required before.  i.e. If I see an error and you raise an alert message to splunk or whatever, I don't need another alert message for the same exact issue.

**Comment by Ferritt1975** [comment]
Correct.  Perhaps the notification is a wrapper function with multiple outputs- slack, email, SNS, SMS, etc. If so, then the "chattiness arrestor" would be relevant across all methods.

**Comment by microtodd** [comment]
Yeah that's why there's that empty method notify with todo written in it. That was the intent.

**Comment by Ferritt1975** [comment]
ah... ok i see it now.  thanks!

**Comment by microtodd** [comment]
fixed in V0.7

**Comment by microtodd** [comment]
I meant V0.8
